### ISSUE TITLE
[BUG]crush app

### ISSUE THREAD

**Issue by quannv98k3** [Cyrexxis/RokTracker#102]
I copied this error log in log file.
The app crushed.

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RokTracker\\deps\\inputs\\kingdom_1_person_scroll.txt'
2024-08-17 15:36:54 scanner INFO Kills for BigMᴀxɪмus2 (78701409) reconstructed, t1 might be off by up to 4 kills.
2024-08-17 15:37:05 kingdom_scanner_ui CRITICAL Uncaught exception
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "kingdom_scanner_ui.py", line 607, in launch_scanner
    "760x200",
  File "roktracker\kingdom\scanner.py", line 513, in start_scan
    track_inactives,
           ^^^^^^^^^
  File "roktracker\kingdom\scanner.py", line 233, in scan_governor
    )
  File "roktracker\utils\adb.py", line 121, in adb_send_events
    except:
            
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RokTracker\\deps\\inputs\\kingdom_1_person_scroll.txt'

**Comment by Cyrexxis** [comment]
Hello. It complains that the scroll script is missing. Normally that should not happen. That file got moved to a different folder with one of the last commits, but there also the python file got changed to work with the change. It's best to only use the released versions instead of cloning this repository if you do not intent to change some things.
