### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dan799434** [Cyrexxis/RokTracker#106]
When i try to run the gui i get the following error, i followed all instructions for the simple mode

Traceback (most recent call last):
  File "kingdom_scanner_ui.py", line 661, in <module>
  File "kingdom_scanner_ui.py", line 479, in __init__
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid \escape: line 21 column 29 (char 451)

**Comment by Cyrexxis** [comment]
Hello sorry for the late response. It looks like something is wrong in the json config file. Probably the path to the bluestacks config. In json you need to use ```\\``` instead of ```\``` otherwise you get this error.

**Comment by dan799434** [comment]
No problem. I discovered this straight after I posted. Works well but I
keep getting banned for using it. Any tips to try and avoid this?
