### ISSUE TITLE
[BUG] RuntimeError: Failed to init API, possibly an invalid tessdata path

### ISSUE THREAD

**Issue by waresr** [Cyrexxis/RokTracker#39]
Traceback (most recent call last):
  File "C:\Users\tuna7\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\tuna7\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tuna7\Desktop\RokTracker-3.0.0\rok_scanner.py", line 1183, in start_from_gui
    scan(
  File "C:\Users\tuna7\Desktop\RokTracker-3.0.0\rok_scanner.py", line 883, in scan
    governor = governor_scan(
               ^^^^^^^^^^^^^^
  File "C:\Users\tuna7\Desktop\RokTracker-3.0.0\rok_scanner.py", line 452, in governor_scan
    with PyTessBaseAPI(path=str(tesseract_path)) as api:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
RuntimeError: Failed to init API, possibly an invalid tessdata path: C:\Users\tuna7\Desktop\RokTracker-3.0.0\deps\tessdata

**Comment by waresr** [comment]
I found a similiar issue posted on the site, but as recommended there tessdata is in deps folder and also the most recent "tessdata-main" folder is with traineddata folders from this link; https://github.com/tesseract-ocr/tessdata

**Comment by Cyrexxis** [comment]
Sorry for the late reply. With version 3 you need a tessdata folder in deps and not tessdata-main (it's also shown in the readme).
