### ISSUE TITLE
[BUG] Uncaught Exception when starting Kingdom Scan

### ISSUE THREAD

**Issue by zabotel** [Cyrexxis/RokTracker#76]
Receive this error anytime I'm running a kingdom scan no matter the scanner settings:

```
2024-03-11 00:36:50 kingdom_scanner_ui CRITICAL Uncaught exception
Traceback (most recent call last):
  File "PIL\ImageFile.py", line 515, in _save
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "kingdom_scanner_ui.py", line 607, in launch_scanner
  File "roktracker\kingdom\scanner.py", line 513, in start_scan
  File "roktracker\kingdom\scanner.py", line 207, in scan_governor
  File "tesserocr.pyx", line 1679, in tesserocr._tesserocr.PyTessBaseAPI.SetImage
  File "tesserocr.pyx", line 331, in tesserocr._tesserocr._image_buffer
  File "tesserocr.pyx", line 335, in tesserocr._tesserocr._image_buffer
  File "PIL\Image.py", line 2438, in save
  File "PIL\BmpImagePlugin.py", line 449, in _save
  File "PIL\ImageFile.py", line 519, in _save
  File "PIL\ImageFile.py", line 530, in _encode_tile
SystemError: tile cannot extend outside image
```
STR:
1. Open Kingdom Scanner (GUI).exe
2. Click Start Scan
3. Wait about 20 seconds
4. Error Occurs

**Comment by Cyrexxis** [comment]
Thanks for the report, I will look into it.

**Comment by Cyrexxis** [comment]
This seems to be related to issue #81 indirectly. But the main problem seems to be that tesseract gets an empty image when the wrong instance is used (and then the image is cut to 0 pixels). Further investigation is needed.
